services:
  database:
    container_name: Learning_jpa
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: learning_jpa
    ports:
      - '5432:5432'